name: Knip

on:
  pull_request:

permissions:
  checks: write
  issues: write

jobs:
  run-knip:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install toolchain
        run: yarn install

      - name: Report knip results to pull request
        uses: Codex-/knip-reporter@v2
        env:
          GITHUB_TOKEN: ${{ secrets.KNIP_TOKEN }}
        with:
          verbose: true
          comment_id: ${{ github.workflow }}-reporter
          command_script_name: knip-ci
          annotations: true
          ignore_results: false