name: Knip-reporter

on:
  workflow_run:
    workflows: ["Knip"]
    types:
      - completed

permissions:
  checks: write
  issues: write


jobs:
  run-knip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install toolchain
        run: yarn install

      - name: Report knip results to pull request
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        uses: gitcoindev/knip-reporter
        with:
          verbose: true
          comment_id: ${{ github.workflow }}-reporter
          command_script_name: knip-ci
          annotations: true
          ignore_results: false
          json_input: true
          json_input_file_name: knip-results.json
