name: Knip

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  checks: write
  issues: write

jobs:
  run-knip:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "static"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/static.zip', Buffer.from(download.data));
      - run: unzip static.zip

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install toolchain
        run: yarn install

      - name: Report knip results to pull request
        uses: Codex-/knip-reporter@v2
        with:
          verbose: true
          comment_id: ${{ github.workflow }}-reporter
          command_script_name: knip-ci
          annotations: true
          ignore_results: false
